# Generated by Django 5.1.4 on 2025-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
