# Generated by Django 5.1.4 on 2025-01-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='place',
        ),
    ]
